name: Hello Triage

on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - opened
      - labeled

jobs:
  triage:
    runs-on: windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup/setup-python@v2

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file

      - name: Execute Python Script
        run:
          # Replace 'your_script.py' with the actual name of your Python script
          python my.py
